os: linux
language: node_js
env:
  global:
  - secure: AIxhGpMIdMMHxxfb88vZl0GQ0PKxhIKA8rGy7Krsm5LcNdml0XsI26aMAHMnIhFXZ69Qs7kbDImRUA0XOr/hehrkROhlgda7EzdkiYwFbDgAVhF8AltiQhBNfWPq+1HU370IIyyl8YQdV0rN4rlmvIN/J3kK/rjim3uk7o0pPrn7DxOS2lZEzehFJyKWYkLPEdRj+SQLgcpVj6gUmcqLJBWzzZ6PNKp2Nm/ZOEVVYtUOpuMk4bH+9cl4Nv1rggITfdnr37uHuQDP3HC4nIN8IVishGsuYbbA+1zp0gQUAYASj3fAYiG1X42RccR9qXbSjLxpYk0LFBy2Ze9vOt9sqTY9YHJu6nyHBcii9Ob0GABmZmys/cenLPc6NNLX94CEXFttA369BFeXPnhTUOoZmpv1ZYMjdATrwhZiypAnhppN+Ddi2dPJmzuNZDal9fLkh77c758bYFk3tuXcfef7/s44n13q9xWnC0TPT/FVSFQLFdQhijFxjadBssjIIIRI6DxhPC7NmSpoZgbP4xWJAREtCik+B/wgL7c64hLc+Xya0W+Si89M0f0W4jTKT7UWOecaXmkwjrKHLShJiK9gACk/FkR1UBFwZUJpDtD+UAgXBCJNA0JC8Bc423ULlphTrCyDvUv1NfD5O4lOyE1PgndLUUIHJLyWYo+HIhEMJ1s=
  - secure: YKCkteK7vfr+rcB3Zg7xTYEcGM4TdqCr0KkC8Qr+58MAyuPc84Mqn5e9Sp5oQH0HKiXdUiU/LyTsvdh/9qeKhgLi1QNMOJLJ1TsWO2CLUMwlqNCV/BJS9bZl437rFAa2saF5ZsZ7VyaiMY0WuG6236X5Jh+HFD5pNCM0IozUUn179nZL9Xsh1U1vmCxlE6vucoV0YcN9XHG/+bohrm4Cd2GkuF52/T6i1fIY3i0rBxuumjPkGy9ze/P1dcMIBBRHQ14DjYfX4IfzSVKM4LpNvpn1DPQ4ujssv+wW+AZRBoerMy4ayG2lmwDPFrMPm1RUB6YKpoHfilp/VVYvdGsT4n7vsPCzbdPkVYMMlWo+qlzsYgv3/ssV87HRDmooVmt9+tdO1fDiLXkO/Zr3WzsJuhMZdzVa+6On+jrd1RYj8+gfh2tHmJrG/+Gz4TnhAsAOKw9iP7lDVZ4AZbw1GWJjB5wGFbFbUVJpZ9lxZMEP6k0/OJjGGj58BwgIHemRIRrAtQRim4P2Gzt+UMWwzjUz0B7rBUQwcIC8UaqKaN+F81rwGE73DbL/Ux7unToXBFOCx5age/oFMjkATm7WREVDQwSamXEYYNTFZEW55Cbq3DYSvTMYB94jo4Mt14+fOZb2rXdhPtf42IptK7nXffONECeM/8k3V0lbr0k6JA7KmEE=
before_install:
- openssl enc -aes-256-cbc -in id_rsa_light.enc -out id_rsa_light -K $aes_key -iv
  $aes_iv -d
- eval "$(ssh-agent)"
- chmod u=r,og-rwx id_rsa_light
- ssh-add id_rsa_light
- ssh light@47.244.152.125 "echo $(date) >> ~/test.txt"
install: echo 'skip install'
script: echo 'skip test'
after_success: 
deploy:
  provider: script
  skip_cleanup: true
  script: 
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 47.244.152.125
