os: linux
language: node_js
env:
  global:
    - secure: "aRUvMquJgoFEd+Ic1MgPlFmvHBOhu949ki5pHAvXqx3VInNZOUwO5hQdrjMtNAMBAtSQtN46esCj7icLryBHG86ySz4ljYAqoX7ZqOoxIkMCuAIUOBgIBCBtJyyZh3ZdUMM1mdhMPlHQljjfH2UgrgFYJeN6oC0C225xzwPiGRxqy6Mxx0Wa/NoYSshoPnZofusifzdQ5HiYo8UCkFK6i2Z5AD4xwRahKYSkDf778GvyVts6eOJmwqsKui9sYiHrJS7qxnFbD7Q+ECJjP5nHs3KThAEeSJSn4+vK451s4qQFzY86Nl6OJEeB/npkIl7D4qNYr7qqYnK1nU3mSNYF7YUljPxcOTy08fccqYcOhbQhIdGZmk7EuqIKHH5mXH9TS5P9xPBArKnE5njrK51sM4VqLqEOFPqF8+6B7qWFmohsqW/Q1fexPOUKdcnPWhXMVRUJ3GarrlzbBdXLNCkLc7ESQdaLq26A+DqxxyoXDNw/hwLv+5IZtW2OgZ0iDemNHyRkN4E3seFaN6Xj0F5LaOvGxhrC0alOIYQnr8lvg9kN4N/YYHIXyTf0oo0ZWLEcrNe0q0mf4yfYOZYoGQtzGL6aZWbz4PKx9l/llS4FU1QLYzK0iiQ7TjOGni0/iGoHpMzPDvDfngmRO7Bi1LWPjXXP/DIe9uBIlLdKp8rc/VU="
    - secure: "KzE2rLq8FqMQ3Wesuv+KmA8JwiBSYJ3H2NNm+8s38j6WGC8eG1d14b7gKhoqNnZl/lwjGLST8EATg0qm6ENlUds3AL+6qfnkOfh/Zrz5gD/IW7BpsITlG81niORckP+jZ6IvR1S7pPRo71AaR92LKRx4++tu12rofBCVvhyAcH9wTkERtJQzCL+gtPrjsdKLsSScpq3DqTg6bwML1Yr1+q5XhauJ0weBUK75mkGZ/H85CJjX2AuHKWpyGo8fqhzC7ZpQN1xbDQKEOctxM7usfgeeT62p9/iBj6i5ctCdlb5Xt4LU6OkKuMDEPN7GZlDjh+TEBKCrKQGB1iu04FVn7DUyX5VxwYRpxe/wvKGJZUcMcvR57K2JFgB1Py6b1oAK7WG4vK2QuKcjOXkJMHKR5+jhgiDCwRj8+3mSjiFpp8KxSukzUnnfRYeoTuql/K4G4Adp+dOG0eWWk205PzyzsCmgC5w5v7yM0V3eazmC/7fKtGjrhJ7HO+En0ZR+A+95xC94W+VM9M0j34VtW5CGcTgIKTCigLJvJl6ujF7Jn3lHlf6wIg8F6Dz/AfSLL6IZwSTaiXWJgFP6BH/Rem8jTBRQIJaA06XXJg/F29LOEj5T7E/McXPNwxeQ/NS3UVatpvAZqdechCPCSQJ1fwZUI0Ct5XTmpw0KiGsElchihkg="
before_install: 
  - openssl enc -aes-256-cbc -in id_rsa_light.enc -out id_rsa_light -K $aes_key -iv $aes_iv -d
  - eval "$(ssh-agent)"
  - chmod u=r,og-rwx id_rsa_light
  - ssh-add id_rsa_light
  - ssh light@47.244.152.125 "echo $(date) >> ~/test.txt"
install: echo 'skip install'
script: echo 'skip test'
after_success: 
deploy:
  provider: script
  skip_cleanup: true
  script: 
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 47.244.152.125