os: linux
language: node_js
env:
  global:
  - secure: rqN1J2EWgZvlZz8HrzDWF80PyGrFBL+BPJxJBRnR+OcvdBItxdgY7XM3hn3A8+n/Vy17Yd8FiTzezLMiR4ApowXv45MDTWnrHZlT0X9uoRS//Rygvd9MbxP9GivMzGIgSPkYdYffxN9B917zhy2zG/iHQrMVercBXDHFpHKA3GozyahcNqAwZhe0WgmeBcx5cv3rvHMIQIVo+mysAWhILyPBrETU2uqgaTEztIBvYANxPoNnlGpdcgekZNVwCZ8UHeagyX8lEpIb9GVEBASqDtO2n4a7bg3SQD2V3bQ8a+6Ddy39WYAMWHoJhJoyR4WChV+J8M59hrByc4BMhgWdGQYu8fomhgbqOBvHNTOa+jZAS7N16vfN44wiu5YZcEIwZ7cwSa/VFY5Z8ZzE/W9BQfgj3luX+B2d1gg8RFkC8L3uFwpVYzT60fUbOjjm5flHPMpIH2XlHFWzyTMYkCua9KZZgQIEnJUdnF9oCygaVXCmdowLpOXzLNXXbR2sqywtAtlxyhPGSUcc2L8Guj4rEPIfU2HGFqYs+67dcsIO6XTqetqHXU6JlNBKdxsITOKb94TdyBSTivB6QKt7SITdssdn+X+B3sk4nm9ld3ibatObd+fQGD7nI4CxX6R4aWRxAJ4BamaJmSTxQddMvmGGtjFQK3z2VUlV6jl3sT7Ci2E=
  - secure: XPUFsb6G389xsyjWkpGLQh/RuczOaSdRYWTDnsjHdh5MRz/xoNBwmZmYj+yRSY1+1dA5yEh2cvMOFreX205V2rbzwsmKLqWqugV0bBgHsm9Cc4HzP0zj+EIRPywwGpIjemyhQ9HKqHYzUDim1IDiHhqKkPNFrdUtlK4udY5YeXhKDRfy/+08cd6luhNzT4UbfMmCIgtpcFBCDinmmKjKH/FBaGh6OZ3KSvwqyR51g2tfJWU1ystY5xkJeNtfSRqPyDlYE5LNYiyFHSvicG75M9KvOFSFPwwsZqrkqnQuvmHcRAqfR81l8fBrEdLonp/T0tEwgBD85cLgJIyMPxfDVrqOtzfvciajdwIkDu/hfC2Z96JKVInS5CSuQ9TE0rYj/lYZSQ4qPTDciQXrA14yhLnN3l+VL7F4FV7w91SD5JIhxQV8/aihVD77bk2R3XHXkYpVbtHRxHZ76ZBFJSI7O1rnvFRZZGEWFoGhkbMn2DG4RvzjCx8rlMKs2s5CczXhMivN/uAqw0QwHxleW+2E1wKBisoqrdjpJsCFwD0EsT8upSXtQBSeJd0a/QRCoDNibu0d1ypD0Ie8lMVF8J0hioCCWwbN6VgeERfF2x+laMygXOdcqzwl0Ie/w8mDnHB4Q8KMllVTMRU8iF/KMAAmFyLXQnAnwBKMhlikGdCfPsc=
before_install:
- openssl enc -aes-256-cbc -in id_rsa_light.enc -out id_rsa_light -K $aes_key -iv
  $aes_iv -d
- eval "$(ssh-agent)"
- chmod u=r,og-rwx id_rsa_light
- ssh-add id_rsa_light
- ssh light@47.244.152.125 "echo $(date) >> ~/test.txt"
install: echo 'skip install'
script: echo 'skip test'
after_success: 
deploy:
  provider: script
  skip_cleanup: true
  script: 
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 47.244.152.125
