os: linux
env:
  global: 
language: node_js
node_js:
- 8
before_install:
- openssl aes-256-cbc -K $encrypted_6176c71fe03c_key -iv $encrypted_6176c71fe03c_iv
  -in id_rsa_light.enc -out id_rsa_light -d
- eval "$(ssh-agent -s)"
- chmod u=r,og-rwx /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install: echo 'skip install'
script: echo 'skip test'
after_success: 
deploy:
  provider: script
  skip_cleanup: true
  # script: bash  $TRAVIS_BUILD_DIR/deploy/index.sh
  script: ssh light@47.244.152.125 "echo $(date) >> ~/test.txt"
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 47.244.152.125
