os: linux
language: node_js
node_js: 8
env:
  global:
    - secure: "FMfqTQ/0tQ4cWdc9hhUe690FOMi2OlJ6tANu2VCZZSUCIg/IAkgAR2mdAZ2B0BgIwQwvUK3I0r9Y3iAwLzhN9uHRAalXtec4b3i3wtSKeyYI2qrqSg2yJVtMeqaYgXcCzcL8a4KQ6/n96j0OUWNXoTVcoAPbKVOYBirrc3I0fE6agIn/vICWE/jRu4anuK/0xc7WCFVvniZjJcIj3ie7mXZNkLqA14d6rGo5opNwYkbwIe3uH4t9KuyaB/WNhuvX6NDSWIGxZM7tfcE0nRvpR8qo9CTa6cyTDhXbOfatdynFQehpk6z4Ky7ui10CCPNE9pUfV7677+SLDiroiTrFkbmhMQovb2sg+emc3OgkFCwvOqeSkTP8/hsbIDUad5me+pZ4Z1p2tU5deHA6lwJrJeH6rkav6IFNvRkgDun+cYC0+wc4jt14BlZs9pm/bOad7pCc2glquM4A1eWuyBOa5tTIw+5XFoJ61wvE1FlDez725uovEWnURoGlcTOWt7cV2cXt7qRUyG/IGa0PSIVaTZQg4URhT7qbmOt9bf7DriyT2a696aplEnuIDBc9MPpMVsI/4XZ8LMvVo+dBrQ/RJ+y4lC5Sp3uveqhT2oM+6RpDIxqPPLi1O9yfR+hx5tFsN/ylP8QbxSeBqAJFpU7N7vYI0YqlxUILDsUUmrQkNKY="
    - secure: "CsCSCMFcXfAVsANOeEFV0Jx3LK+0wa6a/fT66fyB/TgfYP1PsKFYUiGAi3J1+719C+dzslThhNcGI9ctOa+4dkDHTPuX/ntoa7uzk6AvoU+iBXmgbgXCYWQ7D+Z+DPjL5n8iUS5m6TNCO2ML5lUHQ8pGrIf+b4Ru2DMDlCgXCkLahJL1LdK0+EMv0NQrG8cRlqXSQFXH/kGjzZ/znk7Qc4+YR8B/pDpGcAm7L/UPhSPSgcz2XE5QYMTcNmQogVIFlOrbcqrAQAPrVAxggLEFBOUcfo1ychoQFWmnMM7u3icrsaA7ThtVB2pBnrPvSvjOR5BO/obFWW1oTuklzqvU3lZXP2Wm1BAbCjLy5jCRGm2Nm0CUedkj7boYmj9KQz4z29/d/TguWESkrVAoLfJh0pvgBG7UaT6S7YF9/wskFIEmflbBhFWxnnrdal9r8jeS+gXw589UqVr5okHxgj1JLyef/ywizfMF26s5X90oEvO/39fOFl7BjFReOCLNgViGJBRvxrVSmnFq/qlQGa7Ji2MbsLerpnLOAKxEZ+mLs82QPZ6jZB5QYr13bn3MBzYG8MMSL0vqYtQt762svse/VwlcSCoFcwT5QPuTCsi7YfejOxV0BhouYErQZE25llKIs/4dv+IYLjWMLHqhsZz4/rrqskAbcSmLKBPSGzLZM4E="
before_install:
- echo $SSH_IP,$aes_key,$aes_iv
install: echo 'skip install'
script: echo 'skip test'
after_success: 
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - openssl enc -aes-256-cbc -in deploy/cert/id_rsa_light.enc -out id_rsa_light -K $aes_key -iv $aes_iv -d
    - eval "$(ssh-agent)"
    - chmod u=r,og-rwx id_rsa_light
    - ssh-add id_rsa_light
    - ssh light@47.244.152.125 "echo $(date) >> ~/test.txt"
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 47.244.152.125
