
# 生命周期 https://docs.travis-ci.com/user/job-lifecycle
# 部署 https://docs.travis-ci.com/user/deployment/script/
# 环境变量 https://docs.travis-ci.com/user/environment-variables#defining-encrypted-variables-in-travisyml
# https://docs.travis-ci.com/user/ssh-known-hosts/
# 加密 https://docs.travis-ci.com/user/encrypting-files
# travis encrypt 'SSH_IP="47.244.152.125"' --add
# travis encrypt-file xx --add

# 构建矩阵(在多种环境下进行构建,测试兼容性时有用.) https://docs.travis-ci.com/user/customizing-the-build#build-matrix

git:
  depth: 1
branches:
  only:
  - master
# 如果不希望提交触发ci,可以在提交消息中以"[skip travis]"开头

os: linux
language: node_js
node_js:
  - '8.12.0'

matrix:
include:
  - node_js: '8.12.0' # this is not strictly necessary
    env: foo=bar
  - node_js: '10.16.2'
    env: foo=bar
  allow_failures:
  - node_js: 10.16.2

install: npm install
script: echo 'skip test'

# env:
#   global:
#   - secure: vw2LJoqz6YjCR1/WTZnd4VEz++GBvkNh1UuRXI9eunHWpQJpyanXOzUglRlo3RCUpWDv/Y3m5RRcW8MVPyiPaRoHAHszXfXA8+oW0qZbH0/EfGoQSMnu4nedANQx1mOFbe9PT69KsQvhpAY826CzH36hiFWgVHzT2aH6SSeB+vPPGoVXch+H2OzuonO2WGDKuhrw2k3rRMKNYpwrwirdawK94amm5OehQMnxeVZsQLQVHUWPnQ4QYR7Sgz1pNzZ5fgfpY5AGUGw8vgA++afHhQl5QyPxbln2luSwPE0WmzPknM4DIhGikHbYO3mKZepb8GJbxhOvmQOlmFOLGoC1TYUhBWhea3CUB4FOTNWKgReKMz46BoLhL54lJDUY0t3fa1RSk8WThzwkx/Rn4OVEqfUrNVXNanyH3zJTsJMR6g00gE73JqNNL5bTMGz8IBDfjUlVigoTzzvilcSyadId+WFr/g5WuoCTf3A65bWyrgN4BFVQq2apMNQb2nFcRNz1sHoRMbJn0Q6k6A9eiAVltXQOS3Fl/M0dptqxf1RoVPdXZWjGMhaTTGAWZYL1tkFXtvGk2RFj5qsprxNHuKGENwhsI3hf7jYjqjzuT1G4+hBd836l+hT2b1HX8aKjLG4zcC0+hc5Q9IQPr8k73vI0P9PMA8wdlFuRvhj3F1lOakQ=
#   - secure: Md1U0KpItQXJPxOMQkSPWJqk85JwjEj45KdtKRMJfziB8rAZilnrUg9Ip9WNL/JQE5x0P45XGpej0Els2O55LCfxE+2mm7yoo5zQ2RJr3JyvM1q2/b5m1j3mDUIBjxzxbLvP4IGFiegG2JY8FzMczyRcGxQS0B1ccuq8VHXJkfXZsE7NsuIZsZ8XgEmdMBHmfvwjebI0yJocLiso+4r8iEdCoytJBfeX6/YV+M/LIytFN5RM9/zvwoejXsIbM/g0KVtjR/s/BbcGsZpw9Cph4D9h1Aj1YFlXrN74+KgJnSXU7FcqV7zM6S0l2ptew3mGMk+kdIQJiR9tfK6LeXNImnGY1LYRxVWEpD8FiBKNCg1bZOyHiswaJazQ4q8kvWaYN34ZiKj8yIrqGF6PUDv9o9fMy3upcyHLo0YEltRWJoOUmIK3XhXb/IopuxoX1EsxLs8IQIX8zCoekGvgFTclwaWe/gJ3Hx/WveE0PrMsZ61VvleezGJ2CPkwH4pH/+M4WfapGVhFUHXLDvbStv099D3JfpBIdEm80YYZ7f4h5ptpXX3vqxKB7pAl4suRf/Ljr7q/hmcKSUO/bLoWGV/TLC/lWJUwCLIzxVmwBGclcgTRtSZkhpy7qFh94p/31g3QRZFp/A9K3j/pZ7+B0pcG3AnKbbiKTqjffTGdvV8i1r8=


# before_install:
# - openssl aes-256-cbc -K $encrypted_c395babe9e72_key -iv $encrypted_c395babe9e72_iv
#   -in _script/deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod u=r,og-rwx /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa

# after_success: 
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: bash  $TRAVIS_BUILD_DIR/_script/deploy.sh
#   on:
#     branch: master
# addons:
#   ssh_known_hosts:
#   - 47.244.152.125
