os: linux
language: node_js
env:
  global:
  - secure: QzbnJ2St8a1Aw6pX4+PNKeYHtJWkoTxBFLn3MGJMfpzoJRMl19PX/RAtHp7vC74KEwWutn4MGJJnfg2Q7kgcv4eIdDYIV3snhKD4XtIFg2lY07C7mKbaWej9B6xBBJz205eQeXE8QJKAlmGJwAKUPBfYFZOER6o+InOybVQDSb8XO5/7XgB3AnYa2okyy3XRRaDUSRIPkSwYQbmhuF1obqzliCxUHj736Qb1t2M0yG/gIP6rWsdpgqnVsYtdOO9akmy4IJsAI1tI8i/8LarSpRDJgHWKtnDHTgKYXXO8N/8nHOFWdeJfOZDsjWT+mY1wZ2biZxmWN/0DvYfL9/7K7SZDvX6O8Yk4kJeZQT9nKXyEhgUIz1wvox6riu3GPpwsDsMVJeU6OE0bmpsPtySgdeRnmq6ys+YdcQT5W2jlV/VNWRaFGMMkC7Fv5medZbuyrefwxi9dEpbOkXVKrzL2M9giR7E+mllRRnPSbLUSJ/mBfP1/o+9m5XAqp/k0WPPSkDWrwRebeAy5G55aHu3CTVNgRjRIzF08Gm4EyPazZdjbHa63QXYKlF/qjhxazzBuibVxpYbYnnT4kPc6mN1kL/j91h9HnWPhkJuaYsRP8zNR0mz//7oP4vsnBWB9BVERfRunMG45I06ETBHmLKc6OnaJeNQae4ioFh1OuZS5u9M=
  - secure: ILu7qlrrAne69C0kC3XdlWwz0sW4/WgE1uyvpISepX+qvhO8HsfKsRhDNmakuO+h9CsaeAlcgWa81Fg8gEbAZlHDx/KhjHMDcyWUTdH2PwlUTOHxUoQIMQt6XFRMkaKEsBnsVbkJXmdSOljd3wcAI4zqfHHgcroC73Kt8HHghp4QAtyXQUo9ncDb8gXYGrhfxgjnDsmYTRQcmRwxKyA0+tgQOeVglaSowko7hN6BGQdA4nUwUUQKQrTGcJLD1CE+XHDeoKXd7iBHHhadWElnTbT9JNsoIn6bhn+Jg4ETyFFYQgdUeWpZ4gLkK3u6SoDqq/TIANZauj982fWJTHNeK69Qjz21v1d33HBBs8iGisCmwvr9PU1iVUD5pu1LcIbpou2+bfR+ta6FvYdMSygndHo3qcs8VLArgnGVz0cxlArR5MN+rhfLydsjlArNLPqir7FpCRifvwyaJ9dLKwKRXiRm2ex9fyHjAjahRFuk7KPmxN1wrnf2WwiH48xAG+1LF1RNJLStVbe78oQnLLUUHB/ymkkQ1Oj/Tjt3EpWBclFwOfvipWDFYioHV3Ba5aj4OamQ5Q6yCSb1O0z7B4TWIWrzfL7gMt1k7XHRdNA42FSAjr9+n+Vgp146YcAjoylA6Z34q59Gw6hAiRVdaS9hwalCdunLwNshpjRW6ddsn6g=
before_install:
- openssl enc -aes-256-cbc -in id_rsa_light.enc -out id_rsa_light -K $aes_key -iv
  $aes_iv -d
- eval "$(ssh-agent)"
- chmod u=r,og-rwx id_rsa_light
- ssh-add id_rsa_light
- ssh light@47.244.152.125 "echo $(date) >> ~/test.txt"
install: echo 'skip install'
script: echo 'skip test'
after_success: 
deploy:
  provider: script
  skip_cleanup: true
  script: 
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 47.244.152.125
